//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.example.luban_code;

import com.google.gson.JsonElement;

public final class Tables
{
    public  interface  IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final com.example.luban_code.item.TbItem _TbItem;
    public com.example.luban_code.item.TbItem getTbItem() { return _TbItem; }
    private final com.example.luban_code.equip.TbEquip _TbEquip;
    public com.example.luban_code.equip.TbEquip getTbEquip() { return _TbEquip; }

    public Tables(IJsonLoader loader) throws java.io.IOException {
        java.util.Map<String, Object> tables = new java.util.HashMap<>();
        _TbItem = new com.example.luban_code.item.TbItem(loader.load("item_tbitem")); 
        tables.put("item.TbItem", _TbItem);
        _TbEquip = new com.example.luban_code.equip.TbEquip(loader.load("equip_tbequip")); 
        tables.put("equip.TbEquip", _TbEquip);

        _TbItem.resolve(tables); 
        _TbEquip.resolve(tables); 
    }
}
