//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.example.luban_code.test;
public final class AccessFlag {
    public static final int WRITE = 1;
    public static final int READ = 2;
    public static final int TRUNCATE = 4;
    public static final int NEW = 8;
    /**
     * 位标记使用示例
     */
    public static final int READ_WRITE = 3;
}
