//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.example.luban_code.item;

import com.google.gson.JsonElement;
import java.util.Collections;


public final class TbItem {
    private final java.util.Map<Integer, com.example.luban_code.item.Item> _dataMap;
    private final java.util.List<com.example.luban_code.item.Item> _dataList;
    
    public TbItem(JsonElement __json__) {
        java.util.Map<Integer, com.example.luban_code.item.Item> _tmpDataMap = new java.util.HashMap<Integer, com.example.luban_code.item.Item>();
        java.util.List<com.example.luban_code.item.Item> _tmpDataList = new java.util.ArrayList<com.example.luban_code.item.Item>();
        
        for(com.google.gson.JsonElement _e_ : __json__.getAsJsonArray()) {
            com.example.luban_code.item.Item _v;
            _v = new com.example.luban_code.item.Item(_e_.getAsJsonObject());
            _tmpDataList.add(_v);
            _tmpDataMap.put(_v.id, _v);
        }
        
        _dataMap = Collections.unmodifiableMap(_tmpDataMap);
        _dataList = Collections.unmodifiableList(_tmpDataList);
    }

    public java.util.Map<Integer, com.example.luban_code.item.Item> getDataMap() { return _dataMap; }
    public java.util.List<com.example.luban_code.item.Item> getDataList() { return _dataList; }

    public com.example.luban_code.item.Item get(int key) { return _dataMap.get(key); }

    public void resolve(java.util.Map<String, Object> _tables) {
        for(com.example.luban_code.item.Item v : _dataList) {
            v.resolve(_tables);
        }
    }

}