//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.example.luban_code.item;
public final class EQuality {
    /**
     * 最差品质
     */
    public static final int WHITE = 1;
    /**
     * 蓝色的
     */
    public static final int BLUE = 2;
    /**
     * 紫色的
     */
    public static final int PURPLE = 3;
    /**
     * 最高品质
     */
    public static final int RED = 4;
}
