//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.example.luban_code.item;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.Collections;



public final class Item {
    public Item(JsonObject __json__) { 
        id = __json__.get("id").getAsInt();
        name = __json__.get("name").getAsString();
        desc = __json__.get("desc").getAsString();
        price = __json__.get("price").getAsInt();
        upgradeToItemId = __json__.get("upgrade_to_item_id").getAsInt();
        { if (__json__.has("expire_time") && !__json__.get("expire_time").isJsonNull()) { expireTime = __json__.get("expire_time").getAsLong(); } else { expireTime = null; } }
        batchUseable = __json__.get("batch_useable").getAsBoolean();
        quality = __json__.get("quality").getAsInt();
        exchangeStream = new com.example.luban_code.item.ItemExchange(__json__.get("exchange_stream").getAsJsonObject());
        { com.google.gson.JsonArray _json0_ = __json__.get("exchange_list").getAsJsonArray(); java.util.List<com.example.luban_code.item.ItemExchange> _tmp_exchangeList = new java.util.ArrayList(_json0_.size()); for(JsonElement _e0 : _json0_) { com.example.luban_code.item.ItemExchange _v0;  _v0 = new com.example.luban_code.item.ItemExchange(_e0.getAsJsonObject());  _tmp_exchangeList.add(_v0); } exchangeList = Collections.unmodifiableList(_tmp_exchangeList);  }
        exchangeColumn = new com.example.luban_code.item.ItemExchange(__json__.get("exchange_column").getAsJsonObject());
    }

    public Item(int id, String name, String desc, int price, int upgrade_to_item_id, Long expire_time, boolean batch_useable, int quality, com.example.luban_code.item.ItemExchange exchange_stream, java.util.List<com.example.luban_code.item.ItemExchange> exchange_list, com.example.luban_code.item.ItemExchange exchange_column ) {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.price = price;
        this.upgradeToItemId = upgrade_to_item_id;
        this.expireTime = expire_time;
        this.batchUseable = batch_useable;
        this.quality = quality;
        this.exchangeStream = exchange_stream;
        this.exchangeList = exchange_list;
        this.exchangeColumn = exchange_column;
    }

    public static Item deserializeItem(JsonObject __json__) {
        return new Item(__json__);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 价格
     */
    public final int price;
    /**
     * 引用当前表
     */
    public final int upgradeToItemId;
    public com.example.luban_code.item.Item upgradeToItemId_Ref;
    /**
     * 过期时间
     */
    public final Long expireTime;
    /**
     * 能否批量使用
     */
    public final boolean batchUseable;
    /**
     * 品质
     */
    public final int quality;
    /**
     * 道具兑换配置
     */
    public final com.example.luban_code.item.ItemExchange exchangeStream;
    public final java.util.List<com.example.luban_code.item.ItemExchange> exchangeList;
    /**
     * 道具兑换配置
     */
    public final com.example.luban_code.item.ItemExchange exchangeColumn;


    public void resolve(java.util.Map<String, Object> _tables) {
        this.upgradeToItemId_Ref = ((com.example.luban_code.item.TbItem)_tables.get("item.TbItem")).get(upgradeToItemId);
        if (exchangeStream != null) {exchangeStream.resolve(_tables);}
        for(com.example.luban_code.item.ItemExchange _e : exchangeList) { if (_e != null) _e.resolve(_tables); }
        if (exchangeColumn != null) {exchangeColumn.resolve(_tables);}
    }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "price:" + price + ","
        + "upgradeToItemId:" + upgradeToItemId + ","
        + "expireTime:" + expireTime + ","
        + "batchUseable:" + batchUseable + ","
        + "quality:" + quality + ","
        + "exchangeStream:" + exchangeStream + ","
        + "exchangeList:" + exchangeList + ","
        + "exchangeColumn:" + exchangeColumn + ","
        + "}";
    }
}
